[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "croco_abl1d_tutorial"
authors = [{name = "JorisPianezze", email = "pianezze.joris@gmail.com"}]
dynamic = ["version", "description"]
